
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author kadir
 */
public class AdminEkrani extends javax.swing.JDialog {
    DefaultTableModel AracTablosuModel; 
    DefaultTableModel MusteriTablosuModel; 
    AdminIslemleri adminIslemleri = new AdminIslemleri();
    
    
    /**
     * Creates new form AdminEkrani
     */
    public AdminEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AracTablosuModel  =  (DefaultTableModel) aracTablosuAdmin.getModel();
        MusteriTablosuModel =  (DefaultTableModel) MusteriTablosu.getModel();
        aracGoruntule(adminIslemleri.sorguArac);
        kisiGoruntule(adminIslemleri.sorguMusteri);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        aracTablosuAdmin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fiyatField = new javax.swing.JTextField();
        sehirField = new javax.swing.JTextField();
        markamodelField = new javax.swing.JTextField();
        vitesField = new javax.swing.JTextField();
        yakitField = new javax.swing.JTextField();
        sahibiField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        aracEkleButon = new javax.swing.JButton();
        mesajyazisi = new javax.swing.JLabel();
        kiraAracCheck = new javax.swing.JCheckBox();
        bosAracCheck = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        MusteriTablosu = new javax.swing.JTable();
        dinamikField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        musteriIdField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        telnoField = new javax.swing.JTextField();
        musteriGuncelleButon = new javax.swing.JButton();
        mesajyazisiMusteri = new javax.swing.JLabel();
        musteriSilButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        aracTablosuAdmin.setAutoCreateRowSorter(true);
        aracTablosuAdmin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        aracTablosuAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Sahibi", "Günlük Fiyat TL", "Şehir", "Marka Model", "Vites Tipi", "Yakıt Tipi"
            }
        ));
        aracTablosuAdmin.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(aracTablosuAdmin);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Şehir             ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Marka Model  ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Vites Tipi       ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Yakıt Tipi       ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Günlük Fiyat   ");

        fiyatField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sehirField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        markamodelField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        vitesField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        yakitField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sahibiField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Sahibi           ");

        aracEkleButon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aracEkleButon.setText("Araç Ekle");
        aracEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aracEkleButonActionPerformed(evt);
            }
        });

        mesajyazisi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        kiraAracCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kiraAracCheck.setText("Kiradaki Araçları Göster");
        kiraAracCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiraAracCheckActionPerformed(evt);
            }
        });

        bosAracCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bosAracCheck.setText("Boştaki Araçları Göster");
        bosAracCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosAracCheckActionPerformed(evt);
            }
        });

        MusteriTablosu.setAutoCreateRowSorter(true);
        MusteriTablosu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        MusteriTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Kullanıcı Adı", "E-mail", "Telefon No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MusteriTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusteriTablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MusteriTablosu);

        dinamikField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dinamikField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dinamikFieldKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Dinamik Arama:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("ARAÇ BİLGİLERİ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("MÜŞTERİ BİLGİLERİ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Müşteri Id");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Kullanıcı Adı");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("E-mail");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Telefon No");

        musteriIdField.setEditable(false);
        musteriIdField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        usernameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        emailField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        telnoField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        musteriGuncelleButon.setText("Müşteri Güncelle");
        musteriGuncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriGuncelleButonActionPerformed(evt);
            }
        });

        mesajyazisiMusteri.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        musteriSilButon.setText("Müşteri Sil");
        musteriSilButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriSilButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(aracEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(yakitField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(markamodelField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fiyatField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sahibiField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sehirField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(vitesField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dinamikField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(bosAracCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kiraAracCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(musteriIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(usernameField)
                            .addComponent(emailField)
                            .addComponent(telnoField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(musteriSilButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(musteriGuncelleButon, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mesajyazisiMusteri, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailField, musteriIdField, telnoField, usernameField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sahibiField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fiyatField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sehirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(markamodelField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(vitesField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(yakitField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)
                                        .addComponent(aracEkleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel9)
                                        .addGap(9, 9, 9)
                                        .addComponent(dinamikField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kiraAracCheck)
                                        .addGap(9, 9, 9)
                                        .addComponent(bosAracCheck)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesajyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(musteriIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(musteriGuncelleButon))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(musteriSilButon))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(telnoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))))
                                .addGap(18, 18, 18)
                                .addComponent(mesajyazisiMusteri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fiyatField, markamodelField, sahibiField, sehirField, vitesField, yakitField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {emailField, jLabel12, jLabel13, jLabel7, jLabel8, musteriIdField, telnoField, usernameField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aracEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aracEkleButonActionPerformed
        String sahibi     = sahibiField.getText();
        String fiyat      = fiyatField.getText();
        String sehir      = sehirField.getText();
        String markamodel = markamodelField.getText();
        String vites      = vitesField.getText();
        String yakit      = yakitField.getText();
        
        adminIslemleri.aracEkle(sahibi, fiyat, sehir, markamodel, vites, yakit);
        aracGoruntule(adminIslemleri.sorguArac);
        mesajyazisi.setText("Yeni Araç Eklendi.");
    }//GEN-LAST:event_aracEkleButonActionPerformed

    private void bosAracCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosAracCheckActionPerformed
        if (bosAracCheck.isSelected()){
            aracGoruntule(adminIslemleri.sorgubosArac);
            kiraAracCheck.setSelected(false);
        }
        else {
            aracGoruntule(adminIslemleri.sorguArac);
        }
        
    }//GEN-LAST:event_bosAracCheckActionPerformed

    private void kiraAracCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiraAracCheckActionPerformed
        if (kiraAracCheck.isSelected()){
            aracGoruntule(adminIslemleri.sorgukiraArac);
            bosAracCheck.setSelected(false);
        }
        else {
            aracGoruntule(adminIslemleri.sorguArac);
        }
    }//GEN-LAST:event_kiraAracCheckActionPerformed

    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tablerow = new TableRowSorter<DefaultTableModel>(AracTablosuModel);
        aracTablosuAdmin.setRowSorter(tablerow);
        tablerow.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    
    private void dinamikFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinamikFieldKeyReleased
        String ara = dinamikField.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_dinamikFieldKeyReleased

    private void MusteriTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusteriTablosuMouseClicked
        int selectedrow = MusteriTablosu.getSelectedRow();
        musteriIdField.setText(MusteriTablosuModel.getValueAt(selectedrow,0).toString());
        usernameField.setText(MusteriTablosuModel.getValueAt(selectedrow,1).toString());
        emailField.setText(MusteriTablosuModel.getValueAt(selectedrow,2).toString());
        telnoField.setText(MusteriTablosuModel.getValueAt(selectedrow,3).toString());
    }//GEN-LAST:event_MusteriTablosuMouseClicked

    private void musteriGuncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriGuncelleButonActionPerformed
        int id          = Integer.valueOf(musteriIdField.getText());
        String username = usernameField.getText();
        String email    = emailField.getText();
        String telno    = telnoField.getText();
        int selectedrow = MusteriTablosu.getSelectedRow();
        
        adminIslemleri.musteriGuncelle(id,username,email,telno);
        kisiGoruntule(adminIslemleri.sorguMusteri);
        mesajyazisiMusteri.setText("Müşteri Bilgileri Güncellendi");

    }//GEN-LAST:event_musteriGuncelleButonActionPerformed

    private void musteriSilButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriSilButonActionPerformed
        int selectedrow = MusteriTablosu.getSelectedRow();
        int id =(int) MusteriTablosuModel.getValueAt(selectedrow, 0);
        adminIslemleri.musteriSil(id);
        kisiGoruntule(adminIslemleri.sorguMusteri);
        mesajyazisiMusteri.setText("Müşteri Sistemden Silindi.");
        
        
        
    }//GEN-LAST:event_musteriSilButonActionPerformed

    public void aracGoruntule(String sorgu){
        AracTablosuModel.setRowCount(0);
        ArrayList<Arac> araclar = new ArrayList<Arac>();
        araclar = adminIslemleri.araclarıGetir(sorgu);
        
        if (araclar != null){
            for (Arac arac:araclar ){
                Object[] eklenecek={arac.getId(),
                                    arac.getSahibi(),
                                    arac.getFiyat(),
                                    arac.getSehir(),
                                    arac.getMarkaModel(),
                                    arac.getVitesTipi(),
                                    arac.getYakitTipi() };
                
                AracTablosuModel.addRow(eklenecek);
            } 
        }
    }
    
    
    public void kisiGoruntule(String sorgu){
        MusteriTablosuModel.setRowCount(0);
        ArrayList<Kisi> kisiler = new ArrayList<Kisi>();
        kisiler = adminIslemleri.kullaniciGetir(sorgu);
        if (kisiler != null){
            for (Kisi kisi:kisiler ){
                Object[] eklenecek={kisi.getId(),
                                    kisi.getUsername(),
                                    kisi.getEmail(),
                                    kisi.getTelNo()}; 
                MusteriTablosuModel.addRow(eklenecek);
            }
        } 
    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminEkrani dialog = new AdminEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MusteriTablosu;
    private javax.swing.JButton aracEkleButon;
    private javax.swing.JTable aracTablosuAdmin;
    private javax.swing.JCheckBox bosAracCheck;
    private javax.swing.JTextField dinamikField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fiyatField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox kiraAracCheck;
    private javax.swing.JTextField markamodelField;
    private javax.swing.JLabel mesajyazisi;
    private javax.swing.JLabel mesajyazisiMusteri;
    private javax.swing.JButton musteriGuncelleButon;
    private javax.swing.JTextField musteriIdField;
    private javax.swing.JButton musteriSilButon;
    private javax.swing.JTextField sahibiField;
    private javax.swing.JTextField sehirField;
    private javax.swing.JTextField telnoField;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField vitesField;
    private javax.swing.JTextField yakitField;
    // End of variables declaration//GEN-END:variables
}
