
public class GirisEkrani extends javax.swing.JFrame {
    MusteriIslemleri musteriIslemleri = new MusteriIslemleri();
    AdminIslemleri     adminIslemleri = new AdminIslemleri();
    public static String kullanici_adi;
    public static String parola;
    
    /**
     * Creates new form AracKiralamaSistemi
     */
    public GirisEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kiralamaSistemiLabel = new javax.swing.JLabel();
        epostaLabel = new javax.swing.JLabel();
        parolaLabel = new javax.swing.JLabel();
        girisButon = new javax.swing.JButton();
        ParolaButon = new javax.swing.JButton();
        kaydolButon = new javax.swing.JButton();
        kullanici_adi_alani = new javax.swing.JTextField();
        password_alani = new javax.swing.JPasswordField();
        mesaj_yazisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Araç Kiralama Sistemi");
        setBounds(new java.awt.Rectangle(400, 400, 0, 0));

        kiralamaSistemiLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kiralamaSistemiLabel.setText("ARAÇ KİRALAMA SİSTEMİ");

        epostaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        epostaLabel.setText("Kullanıcı Adı :");

        parolaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        parolaLabel.setText("Parola         :");

        girisButon.setText("Giriş Yap");
        girisButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButonActionPerformed(evt);
            }
        });

        ParolaButon.setText("Parolamı Unuttum");
        ParolaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParolaButonActionPerformed(evt);
            }
        });

        kaydolButon.setText("Kaydol");
        kaydolButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydolButonActionPerformed(evt);
            }
        });

        kullanici_adi_alani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        password_alani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kaydolButon, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(ParolaButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kiralamaSistemiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(girisButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(parolaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(epostaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(kullanici_adi_alani)
                                .addComponent(password_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ParolaButon, girisButon, kaydolButon});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {kullanici_adi_alani, password_alani});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(kiralamaSistemiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epostaLabel)
                    .addComponent(kullanici_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parolaLabel)
                    .addComponent(password_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girisButon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ParolaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kaydolButon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ParolaButon, girisButon, kaydolButon});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {kullanici_adi_alani, password_alani});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girisButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButonActionPerformed
        mesaj_yazisi.setText(""); 
        kullanici_adi = kullanici_adi_alani.getText();
        parola        = new String(password_alani.getPassword());
        boolean girisbasarilimusteri = musteriIslemleri.girisYap(kullanici_adi, parola);
        boolean girisbasariliadmin   = adminIslemleri.girisYap(  kullanici_adi, parola);
        if (girisbasarilimusteri) { 
            MusteriEkrani musteriEkrani = new MusteriEkrani(this,true);
            setVisible(false);
            musteriEkrani.setVisible(true);
            System.exit(0);
        }
        else if (girisbasariliadmin){
            AdminEkrani adminEkrani = new AdminEkrani(this,true);
            setVisible(false);
            adminEkrani.setVisible(true);
            System.exit(0);
        }
        else {
            mesaj_yazisi.setText("Giriş Başarısız");
        }
    }//GEN-LAST:event_girisButonActionPerformed

    private void kaydolButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydolButonActionPerformed
        KaydolEkrani kaydolEkrani = new KaydolEkrani(this,true);
        kaydolEkrani.setVisible(true);
    }//GEN-LAST:event_kaydolButonActionPerformed

    private void ParolaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParolaButonActionPerformed
        ParolaUnuttumEkrani parolaUnuttumEkrani = new ParolaUnuttumEkrani(this,true);
        parolaUnuttumEkrani.setVisible(true);
    }//GEN-LAST:event_ParolaButonActionPerformed

    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ParolaButon;
    private javax.swing.JLabel epostaLabel;
    private javax.swing.JButton girisButon;
    private javax.swing.JButton kaydolButon;
    private javax.swing.JLabel kiralamaSistemiLabel;
    private javax.swing.JTextField kullanici_adi_alani;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JLabel parolaLabel;
    private javax.swing.JPasswordField password_alani;
    // End of variables declaration//GEN-END:variables
}
